services:
  db:
    image: mysql/mysql-server:8.0.23
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=emp
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345678
    ports:
      - 3306:3306
    networks:
      - app-network

  app:
    image: demo/sre-challenge
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/emp?allowPublicKeyRetrieval=true&useSSL=false&requireSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345678

networks:
  app-network:
    driver: bridge
