apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: sre-challenge
type: Opaque
data:
  mysql-username: cm9vdA== # "root" em base64
  mysql-password: MTIzNDU2Nzg= # "12345678" em base64
  mysql-root-password: MTIzNDU2Nzg= # "12345678" em base64
  mysql-database: ZW1w # "emp" em base64
