apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: sre-challenge # Adicionado o namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: mysql/mysql-server:8.0.23
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "12345678"
            - name: MYSQL_DATABASE
              value: "emp"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "12345678"
