apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: sre-challenge
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8080 # Porta interna do serviço
      targetPort: 8080 # Porta interna do pod
      nodePort: 30080 # Porta externa (para acessar fora do cluster)
  type: NodePort
