---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: sre-challenge # Adicionado o namespace
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None
